FROM java:8
# Rocketmq version
ENV ROCKETMQ_VERSION 4.2.0
# Rocketmq home
ENV ROCKETMQ_HOME  /opt/rocketmq-${ROCKETMQ_VERSION}
WORKDIR  ${ROCKETMQ_HOME}
RUN mkdir -p \
        /opt/logs \
        /opt/store
ADD rocketmq-all-4.2.0-bin-release.zip rocketmq.zip
RUN       unzip rocketmq.zip \
          && rm rocketmq.zip
RUN chmod +x bin/mqbroker
CMD cd ${ROCKETMQ_HOME}/bin && export JAVA_OPT=" -Duser.home=/opt" && sh mqbroker -n namesrv:9876
EXPOSE 10909 10911
VOLUME /opt/logs \
        /opt/store